version: '3.3'

services:
  nut_api:
    image: node:14
    container_name: nut_api
    working_dir: /app
    ports:
      - '4000:4000'
    volumes:
      - .:/app
    command: bash -c "npm install && npm run start"