version: '3.3'

services:
  nut_api:
    image: node:14
    container_name: nut_api
    working_dir: /app
    ports:
      - '4000:4000'
    volumes:
      - .:/app
    depends_on:
      - db
    command: bash -c "npm install && npm run dev"

  nut_db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db:/var/lib/postgresql/data
    container_name: nut_db
    
volumes:
  postgresql:
  postgresql_data: 
  db:
