version: '3.3'

services:
  api:
    image: node:14
    container_name: api
    working_dir: /app
    ports:
      - '4000:4000'
    volumes:
      - .:/app
    depends_on:
      - db
    command: bash -c "npm install && npm run dev"

  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db:/var/lib/postgresql/data
    container_name: db

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
      - PGADMIN_LISTEN_PORT=5050
    ports:
      - "5050:5050"

    
volumes:
  postgresql:
  postgresql_data: 
  db:
